name: Deploy 1

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: connery-io/deploy-plugin-on-aws-lambda/run-tests@main

      - uses: connery-io/deploy-plugin-on-aws-lambda/build-and-deploy@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          backend-config: backend_v1.hcl
